name: Build Wrapper Linux Arm64

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: DigitalAssistant
        
    - uses: uraimo/run-on-arch-action@v2
      name: Build PhonemizeESpeakWrapper
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu_latest
        githubToken: ${{ github.token }}
        install: |
          apt-get update -q -y
          apt-get install -q -y make
          apt-get install -q -y build-essential
        run: |          
          make export_aarch64 -C DigitalAssistant/Libs/PhonemizeESpeakWrapper
        
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        path: DigitalAssistant/Libs/PhonemizeESpeakWrapper/Export/
