name: Build Wrapper Windows x86/x64

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: DigitalAssistant
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Build PhonemizeESpeakWrapper
      run: msbuild DigitalAssistant/Libs/PhonemizeESpeakWrapper/PhonemizeESpeakWrapper.vcxproj /p:configuration=Release /p:platform=x64 /p:OutDir=${{ github.workspace }}/Wrapper
    
    - name: Configure Release Settings
      shell: pwsh
      run: |
        Write-Host "Remove no longer required configuration files"
        
        $basePath =  "${{ github.workspace }}"
        Copy-Item -Path (Join-Path $basePath "DigitalAssistant\Libs\TextToSpeech\Libs\piper-phonemize-windows-bin\espeak-ng.dll") -Destination (Join-Path $basePath "Wrapper\espeak-ng.dll")
        Copy-Item -Path (Join-Path $basePath "DigitalAssistant\Libs\TextToSpeech\Libs\piper-phonemize-windows-bin\piper_phonemize.dll") -Destination (Join-Path $basePath "Wrapper\piper_phonemize.dll")
        
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        path: Wrapper/
