name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: DigitalAssistant

      - name: Clone BlazorBase
        uses: actions/checkout@v4
        with:
          repository: PALs-Software/BlazorBase
          ref: develop
          path: BlazorBase

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digital-assistant-server:latest
          context: "${{ github.workspace }}"
          file: "${{ github.workspace }}/DigitalAssistant/Scripts/Build/Dockerfile"